[package]
name = "netlink-packet-utils"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
failure = "0.1.6"
paste = "0.1.6"
