[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
name = "netlink-proto"
version = "0.2.0"
edition = "2018"

homepage = "https://github.com/little-dude/netlink"
keywords = ["netlink", "linux", "async"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/little-dude/netlink"
description = "async netlink protocol"

[dependencies]
bytes = "0.5.3"
log = "0.4.8"
futures = "0.3.1"
failure = "0.1.6"
tokio = { version = "0.2.6", default-features = false, features = ["io-util"] }
tokio-util = { version = "0.2.0", default-features = false, features = ["codec"] }
netlink-packet-core = { path = "../netlink-packet-core" }
netlink-sys = { path = "../netlink-sys", default-features = false, features = ["tokio_socket"] }

[features]
default = []
workaround-audit-bug = []

[dev-dependencies]
env_logger = "0.7.1"
tokio = { version = "0.2.6", default-features = false, features = ["macros", "rt-core"] }
netlink-packet-route = { path = "../netlink-packet-route" }
netlink-packet-audit = { path = "../netlink-packet-audit" }

[[example]]
name = "dump_links"

[[example]]
name = "audit_events"
required-features = ["workaround-audit-bug"]
