[package]
name = "rtnetlink"
version = "0.0.2"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
edition = "2018"

homepage = "https://github.com/little-dude/netlink"
keywords = ["netlink", "ip", "linux"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/little-dude/netlink"
description = "manipulate linux networking resources via netlink"

[dependencies]
bytes = "0.4.11"
tokio-core = "0.1.17"
tokio = "0.1.13"
futures = "0.1.25"
log = "0.4.6"
lazy_static = "1.2.0"
failure = "0.1.4"
failure_derive = "0.1.4"

[dependencies.netlink-packet]
version = "0.0"
default-features = false
features = ["rtnetlink"]
path = "../netlink-packet"

[dependencies.netlink-proto]
version = "0.0"
default-features = false
features = ["rtnetlink"]
path = "../netlink-proto"

[dev-dependencies]
env_logger = "0.6.0"
ipnetwork = "0.13.1"
