name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  ci:
    name: CI (stable)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: test (netlink-sys)
        run: |
          cd netlink-sys
          cargo test
          cargo test --features tokio_socket

      - name: test (netlink-packet-audit)
        run: |
          cd netlink-packet-audit
          cargo test

      - name: test (netlink-packet-core)
        run: |
          cd netlink-packet-core
          cargo test

      - name: test (netlink-packet-generic)
        run: |
          cd netlink-packet-generic
          cargo test

      - name: test (netlink-packet-route)
        run: |
          cd netlink-packet-route
          cargo test
          cargo test --features rich_nlas

      - name: test (netlink-packet-sock-diag)
        run: |
          cd netlink-packet-sock-diag
          cargo test

      - name: test (netlink-packet-utils)
        run: |
          cd netlink-packet-utils
          cargo test

      - name: test (netlink-proto)
        run: |
          cd netlink-proto
          cargo test

      - name: test (rtnetlink)
        env:
          # Needed for the `link::test::create_get_delete_w` test to pass.
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: "sudo -E"
        run: |
          cd rtnetlink
          cargo test

      - name: test (audit)
        run: |
          cd audit
          cargo test

      - name: test (genetlink)
        run: |
          cd genetlink
          cargo test --features tokio_socket

      - name: test (ethtool)
        run: |
          cd ethtool
          cargo test
